### ISSUE TITLE
Which Map do you use in Covid-19 dashboard?

### ISSUE THREAD

**Issue by ofyayla** [MicrosoftDocs/powerbi-docs.tr-tr#3]
I am trying to make the same dashboard, but I didn't find which the map you use.

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: 7c22af6d-1ae9-9288-51b6-8d05c51d1b56
* Version Independent ID: bd77226f-99c4-9f7f-c353-7fa0891a891c
* Content: [ABD eyalet ve yerel hükümetlere yönelik COVID-19 izleme örneği - Power BI](https://docs.microsoft.com/tr-tr/power-bi/create-reports/sample-covid-19-us)
* Content Source: [powerbi-docs/create-reports/sample-covid-19-us.md](https://github.com/MicrosoftDocs/powerbi-docs.tr-tr/blob/live/powerbi-docs/create-reports/sample-covid-19-us.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @LukaszPawlowski-MS
* Microsoft Alias: **lukaszp**

**Comment by srvbpigh** [comment]
Hello, @ofyayla
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Merhaba @ofyayla,  

Katkılarınıza çok değer veriyoruz. Geri bildiriminiz orijinal belgelerle ilgili.  

Bu nedenle bu sorunu İngilizce deposuna geçiriyoruz. Lütfen sorunun durumunu buradan gözden geçirin - https://github.com/MicrosoftDocs/powerbi-docs/issues/2084.  

Makalelerimize yaptığınız katkılar bizim için çok değerlidir.   

Saygılarımla,  
Microsoft DOCS Uluslararası Ekibi
