### ISSUE TITLE
Power BI

### ISSUE THREAD

**Issue by fthshn** [MicrosoftDocs/powerbi-docs.tr-tr#5]
[Geri bildiriminizi buraya girin]

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: df058604-4117-88d8-0cb0-935d08e5b22a
* Version Independent ID: dc8d3604-1fea-0109-2a94-13bd70a10522
* Content: [Power BI'da çalışmanızı paylaşmanın yolları - Power BI](https://docs.microsoft.com/tr-tr/power-bi/service-how-to-collaborate-distribute-dashboards-reports)
* Content Source: [powerbi-docs/service-how-to-collaborate-distribute-dashboards-reports.md](https://github.com/MicrosoftDocs/powerbi-docs.tr-tr/blob/live/powerbi-docs/service-how-to-collaborate-distribute-dashboards-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srvbpigh** [comment]
Hello, @fthshn
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-radelg** [comment]
Merhaba @fthshn , 
Yorumunuzu takdir ediyor ve docs.microsoft.com deneyiminizi geliştirmeye çalışıyoruz. Öte yandan, geri bildiriminizle ilgilenmek için daha fazla bilgiye ihtiyacımız var. Lütfen daha ayrıntılı bilgi sağlayın ve yorumunuzu netleştirin. Saygılarımızla, 
Microsoft DOCS Uluslararası Ekibi

**Comment by CeciAc** [comment]
Merhaba @fthshn 

Yorumunuz için tekrar teşekkürler. 

Ne yazık ki hala eksik bilgileri alamadık ve geri bildiriminizle ilgili işlem yapamıyoruz. Şu anda bu GitHub sorununu kapatıyoruz ama gelecekte daha fazla geri bildirim göndermenizi öneririz. 

Saygılarımızla, 

Microsoft DOCS Uluslararası Ekibi
